strictPeerDependencies: false
shamefullyHoist: true
shellEmulator: true

packages:
  - proxy

patchedDependencies:
  nuxt-nightly@4.6.0-29803612.ea5d49fb: patches/nuxt-nightly@4.6.0-29803612.ea5d49fb.patch

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  sharp: false
